# ============================================================
# 应用程序配置文件 
# 修改后重启应用即可生效 
# ============================================================ 

# 默认区域: 启用 IS_USE_DEFAULT_REGION 时生效
DEFAULT_REGION = "CN"


# ============================================================
# 服务器路由配置
# ============================================================
[SERVER_ROUTE]
MANIFEST_ROUTE = "/meta/win.html"
RESOURCE_ROUTE = "/res/win/"


# ============================================================
# 文件路径配置
# 注意：所有路径都是相对于程序运行目录
# ============================================================
[FILE_PATH]
ROOT_OUTPUT_DIR = "./output/"
MANIFEST_OUTPUT_DIR = "./output/Manifest"
VERSIONS_OUTPUT_DIR = "./output/Manifest"
PATCH_OUTPUT_DIR = "./output/Metadata"
UNPACK_OUTPUT_DIR = "./output/Unpack"


# ============================================================
# 文件名配置
# ============================================================
[FILE_NAME]
MANIFEST_RAW_FILE = "win.html"
MANIFEST_DECRYPT_FILE = "win.bytes"
MANIFEST_DECODED_FILE = "resource_manifest.json"
PATCH_MANIFEST_FILE = "patch_manifest.json"
VERSION_FILE = "version.json"
UPDATE_ROOT_MANI_FILE = "ss_win.mani"
UPDATE_RESOURCE_PATCH_TAG_PREFIX = "p_"
UPDATE_RESOURCE_PATCH_TAG_SUFFIX = "_u"
UPDATE_MANIFEST_PATCH_TAG_SUFFIX = "_m"
UPDATE_MANIFEST_EXTENSION = ".mani"
UPDATE_FIRST_MANIFEST_PATCH_NAME = "p_1_m.ss_win.mani"
UPDATE_ADD_MANIFEST_NAME = "ss_win_add.mani"


# ============================================================
# 提取器配置
# 当前应用于 .mani 文件 version 提取 key (DO NOT EDIT)
# ============================================================
[EXTRACTOR]
DEFAULT_VERSION_KEY = "unknown"
CLIENT_VERSION_KEY = "CLIENT_VER"
GAME_VERSION_KEY = "GAME_VER"
PATCH_VERSION_KEY = "BIN_DIFF_PATCH_VER"


# ============================================================
# HTTP 请求配置
# 如果网络不好或者文件太大, 请求读取 body 会超时
# 可适当增加 TIMEOUT_SECS 来避免(特别是 lua.arcx )
# ============================================================
[REQUEST]
VERIFY_TLS = false
TIMEOUT_SECS = 180
TOTAL_RETRIES = 2
BACKOFF_FACTOR = 3
POOL_MAX_IDLE = 50
MIN_RETRY_DELAY_MS = 500
MAX_RETRY_DELAY_SECS = 30

[REQUEST.EXTRA_HEADERS]
Accept-Encoding = "identity"
X-Unity-Version = "2022.3.62f2"
User-Agent = "UnityPlayer/2022.3.62f2 (UnityWebRequest/1.0, libcurl/8.10.1-DEV)"


# ============================================================
# 资源注册表配置
# ============================================================
[RESOURCE_REGISTRY]
NEED_FETCH_FILES = [
    "lua.arcx",
    "data.arcx",
    "lua.json",
    "data.json",
    "ss_win.mani",
    "ss_win_add.mani",
]
UNPACK_FILES = [
    "lua.arcx",
    "data.arcx",
]


# ============================================================
# 服务器配置: 
# 区域名 = { URL = "服务器地址", KEY = "密钥" }
# KEY: 来自于提取的 ClientConfig.json 的 serverMetaKey 
# ============================================================
[SERVERS.CN]
URL = "https://nova-static.yostar.cn"
KEY = "Xf&FRcsYm48cJ2A@"

[SERVERS.EN]
URL = "https://nova-static.stellasora.global"
KEY = "ma5Dn2FhC*Xhxy%c"

[SERVERS.JP]
URL = "https://nova-static.stellasora.jp"
KEY = "ZnUFA@S9%4KyoryM"

[SERVERS.KR]
URL = "https://nova-static.stellasora.kr"
KEY = "U9cjHuwGDDx&$drn"

[SERVERS.TW]
URL = "https://nova-static.stargazer-games.com"
KEY = "owGYVDmfHrxi^4pm"


# ============================================================
# 功能开关
# 注意: IS_SAVE_PATCH_MANIFEST 必须是 true
# 因为合并补丁需要读取补丁清单和校验清单中的 hash
# ============================================================
[FEATURE_FLAGS]
IS_USE_DEFAULT_REGION = false
IS_SAVE_RAW_MANIFEST = false
IS_SAVE_DECRYPTED_MANIFEST = false
IS_SAVE_DECODED_MANIFEST = true
IS_EXTRACT_PATCH_MANIFEST = true
IS_SAVE_PATCH_MANIFEST = true
IS_DOWNLOAD_RESOURCE = true
IS_OVERWRITE_RESOURCE = false
IS_MERGE_PATCH = true
IS_SAVE_VERSION_FILE = true
IS_EXTRACT_PATCH_VERSION = true