name: Check manifest

on:
  workflow_dispatch:

permissions:
      contents: write 

env:
  TMP_VERSION_PATH: /tmp/old_manifest/version.json
  OUT_VERSION_PATH: ManifestTool/output/Manifest/version.json

jobs:
  retrieve-manifest:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Restore manifest cache
        uses: actions/cache/restore@v6
        with:
          path: ManifestTool/output
          key: ss-manifest-default
          restore-keys: ss-manifest-
          
      - name: Backup previous version
        run: |
          if [ -f "${{ env.OUT_VERSION_PATH }}" ]; then
            mkdir -p $(dirname "${{ env.TMP_VERSION_PATH }}")
            cp ${{ env.OUT_VERSION_PATH }} ${{ env.TMP_VERSION_PATH }}
            echo "TMP_VERSION_EXISTS=true" >> $GITHUB_ENV
          else
            echo "TMP_VERSION_EXISTS=false" >> $GITHUB_ENV
          fi
        shell: bash
      
      - name: Run manifest tool
        id: run-manifest-tool
        working-directory: ManifestTool
        run: |
          if [ -f "manifest-tool.toml" ]; then
            echo "config_exist=true" >> "$GITHUB_OUTPUT"
          else
            echo "config_exist=false" >> "$GITHUB_OUTPUT"
          fi
          chmod +x ./ManifestTool && ./ManifestTool
        shell: bash

      - name: Compare version.json changes
        id: compare-version-file
        run: |
          if [ "$TMP_VERSION_EXISTS" == "true" ]; then
            if ! cmp -s ${{ env.TMP_VERSION_PATH }} ${{ env.OUT_VERSION_PATH }}; then
              echo "VERSION CHANGED"
              echo "changed=true" >> $GITHUB_OUTPUT
            else
              echo "VERSION NO CHANGE"
              echo "changed=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "CHANGED (no previous version)"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Save manifest cache
        if: steps.compare-version-file.outputs.changed == 'true'
        uses: actions/cache/save@v6
        with:
          path: ManifestTool/output
          key: ss-manifest-${{ hashFiles(env.OUT_VERSION_PATH) }}
      
      - name: Commit tool config
        if: steps.run-manifest-tool.outputs.config_exist == 'false'
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "update: manifest-tool.toml"
          file_pattern: "ManifestTool/manifest-tool.toml"

      - name: Trigger workflow
        if: steps.compare-version-file.outputs.changed == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: MakoStar/ss-unpack-bot
          workflow: unpack-lua.yml
          token: ${{ secrets.GH_TOKEN }}
